package database

const testData string = `
[
  {
    "title": "The Hunger Games",
    "description": "In the ruins of North America lies the nation of Panem, where twelve districts are forced to send tributes to a televised fight to the death.",
    "year": 2008,
    "isbn": "9780439023481",
    "asin": "B002MQYOFW",
    "tags": ["Dystopian", "Survival", "Young Adult"],
    "publisher": "Scholastic Press",
    "series": [{"name": "The Hunger Games", "index": "1"}],
    "authors": [{"name": "Suzanne Collins"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Tatiana Maslany"}]
  },
  {
    "title": "Catching Fire",
    "description": "Against all odds, Katniss Everdeen has won the annual Hunger Games. But the Capitol is angry and wants revenge.",
    "year": 2009,
    "isbn": "9780439023498",
    "asin": "B003O86FMW",
    "tags": ["Dystopian", "Revolution", "Young Adult"],
    "publisher": "Scholastic Press",
    "series": [{"name": "The Hunger Games", "index": "2"}],
    "authors": [{"name": "Suzanne Collins"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Tatiana Maslany"}]
  },
  {
    "title": "The Eye of the World",
    "description": "The Wheel of Time turns and Ages come and go, leaving memories that become legend.",
    "year": 1990,
    "isbn": "9781250251466",
    "asin": "B002U3CCYQ",
    "tags": ["Epic Fantasy", "High Fantasy"],
    "publisher": "Tor Books",
    "series": [{"name": "The Wheel of Time", "index": "1"}],
    "authors": [{"name": "Robert Jordan"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Michael Kramer"}, {"name": "Kate Reading"}]
  },
  {
    "title": "The Great Hunt",
    "description": "The hunt for the Horn of Valere begins as Rand al'Thor struggles with his destiny.",
    "year": 1990,
    "isbn": "9780312851408",
    "asin": "B004OC7IXM",
    "tags": ["Epic Fantasy", "Adventure"],
    "publisher": "Tor Books",
    "series": [{"name": "The Wheel of Time", "index": "2"}],
    "authors": [{"name": "Robert Jordan"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Michael Kramer"}, {"name": "Kate Reading"}]
  },
  {
    "title": "The Way of Kings",
    "description": "Roshar is a world of stone and storms where life has adapted accordingly.",
    "year": 2010,
    "isbn": "9780765365279",
    "asin": "B003P2S02M",
    "tags": ["Epic Fantasy", "Magic Systems"],
    "publisher": "Tor Books",
    "series": [{"name": "The Stormlight Archive", "index": "1"}],
    "authors": [{"name": "Brandon Sanderson"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Michael Kramer"}, {"name": "Kate Reading"}]
  },
  {
    "title": "Words of Radiance",
    "description": "The Knights Radiant must stand again as the True Desolation approaches.",
    "year": 2014,
    "isbn": "9780765326362",
    "asin": "B00E7V66O6",
    "tags": ["Epic Fantasy", "War"],
    "publisher": "Tor Books",
    "series": [{"name": "The Stormlight Archive", "index": "2"}],
    "authors": [{"name": "Brandon Sanderson"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Michael Kramer"}, {"name": "Kate Reading"}]
  },
  {
    "title": "Oathbringer",
    "description": "Dalinar Kholin faces the secrets of his past to unite a fractured world.",
    "year": 2017,
    "isbn": "9780765326379",
    "asin": "B01NAWAH85",
    "tags": ["Epic Fantasy", "Politics"],
    "publisher": "Tor Books",
    "series": [{"name": "The Stormlight Archive", "index": "3"}],
    "authors": [{"name": "Brandon Sanderson"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Michael Kramer"}, {"name": "Kate Reading"}]
  },
  {
    "title": "Red Rising",
    "description": "Darrow is a Red working the mines of Mars, unaware he is living a lie.",
    "year": 2014,
    "isbn": "9780345539793",
    "asin": "B00CVS2J80",
    "tags": ["Dystopian", "Sci-Fi"],
    "publisher": "Del Rey",
    "series": [{"name": "Red Rising Saga", "index": "1"}],
    "authors": [{"name": "Pierce Brown"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Tim Gerard Reynolds"}]
  },
  {
    "title": "Golden Son",
    "description": "Darrow continues his climb through the hierarchy of the Golds to destroy it from within.",
    "year": 2015,
    "isbn": "9780345539823",
    "asin": "B00I765ZEU",
    "tags": ["Space Opera", "Strategy"],
    "publisher": "Del Rey",
    "series": [{"name": "Red Rising Saga", "index": "2"}],
    "authors": [{"name": "Pierce Brown"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Tim Gerard Reynolds"}]
  },
  {
    "title": "Leviathan Wakes",
    "description": "A ship captain and a detective find themselves in a conspiracy that threatens the solar system.",
    "year": 2011,
    "isbn": "9780316129084",
    "asin": "B0047DVMR2",
    "tags": ["Space Opera", "Mystery"],
    "publisher": "Orbit",
    "series": [{"name": "The Expanse", "index": "1"}],
    "authors": [{"name": "James S. A. Corey"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Jefferson Mays"}]
  },
  {
    "title": "Caliban's War",
    "description": "War comes to the solar system as a monster is unleashed on Ganymede.",
    "year": 2012,
    "isbn": "9780316129060",
    "asin": "B0078XG9S6",
    "tags": ["Space Opera", "Action"],
    "publisher": "Orbit",
    "series": [{"name": "The Expanse", "index": "2"}],
    "authors": [{"name": "James S. A. Corey"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Jefferson Mays"}]
  },
  {
    "title": "Abaddon's Gate",
    "description": "A massive structure opens a gate to the unknown, drawing humanity into a new era.",
    "year": 2013,
    "isbn": "9780316129077",
    "asin": "B00B924Y9U",
    "tags": ["Space Opera", "Exploration"],
    "publisher": "Orbit",
    "series": [{"name": "The Expanse", "index": "3"}],
    "authors": [{"name": "James S. A. Corey"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Jefferson Mays"}]
  },
  {
    "title": "Project Hail Mary",
    "description": "A man wakes up on a spaceship with no memory and a mission to save Earth.",
    "year": 2021,
    "isbn": "9780593135204",
    "asin": "B08FHBV47V",
    "tags": ["Sci-Fi", "Problem Solving"],
    "publisher": "Ballantine Books",
    "series": [],
    "authors": [{"name": "Andy Weir"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Ray Porter"}]
  },
  {
    "title": "Circe",
    "description": "The daughter of Helios finds her power in witchcraft and is banished to a deserted island.",
    "year": 2018,
    "isbn": "9780316556347",
    "asin": "B0759S6F6L",
    "tags": ["Mythology", "Retelling"],
    "publisher": "Little, Brown",
    "series": [],
    "authors": [{"name": "Madeline Miller"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Perdita Weeks"}]
  },
  {
    "title": "The Night Circus",
    "description": "Two young magicians are pitted against each other in a venue that only appears at night.",
    "year": 2011,
    "isbn": "9780307744432",
    "asin": "B004S0TWRU",
    "tags": ["Fantasy", "Romance"],
    "publisher": "Anchor",
    "series": [],
    "authors": [{"name": "Erin Morgenstern"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Jim Dale"}]
  },
  {
    "title": "Atomic Habits",
    "description": "A guide to building good habits and breaking bad ones through small changes.",
    "year": 2018,
    "isbn": "9780735211292",
    "asin": "B07D23CFGR",
    "tags": ["Self-Help", "Productivity"],
    "publisher": "Avery",
    "series": [],
    "authors": [{"name": "James Clear"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "James Clear"}]
  },
  {
    "title": "Where the Crawdads Sing",
    "description": "A young girl growing up in the marsh of North Carolina becomes a murder suspect.",
    "year": 2018,
    "isbn": "9780735219090",
    "asin": "B078N29M55",
    "tags": ["Mystery", "Nature"],
    "publisher": "G.P. Putnam's Sons",
    "series": [],
    "authors": [{"name": "Delia Owens"}],
    "genres": [{"name": "Fiction"}],
    "narrators": [{"name": "Cassandra Campbell"}]
  },
  {
    "title": "Educated",
    "description": "A memoir about a woman born to survivalists who leaves her isolated family to pursue an education.",
    "year": 2018,
    "isbn": "9780399590504",
    "asin": "B072BLVM83",
    "tags": ["Memoir", "Inspiration"],
    "publisher": "Random House",
    "series": [],
    "authors": [{"name": "Tara Westover"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Julia Whelan"}]
  },
  {
    "title": "The Silent Patient",
    "description": "A woman shoots her husband and then never speaks another word.",
    "year": 2019,
    "isbn": "9781250301697",
    "asin": "B07H76B69T",
    "tags": ["Thriller", "Psychological"],
    "publisher": "Celadon Books",
    "series": [],
    "authors": [{"name": "Alex Michaelides"}],
    "genres": [{"name": "Fiction"}],
    "narrators": [{"name": "Louise Brealey"}]
  },
  {
    "title": "Tomorrow, and Tomorrow, and Tomorrow",
    "description": "Two friends collaborate on video game design over thirty years.",
    "year": 2022,
    "isbn": "9780593321201",
    "asin": "B09G967T6L",
    "tags": ["Contemporary", "Gaming"],
    "publisher": "Knopf",
    "series": [],
    "authors": [{"name": "Gabrielle Zevin"}],
    "genres": [{"name": "Fiction"}],
    "narrators": [{"name": "Jennifer Lim"}]
  },
  {
	"title": "The Martian",
	"description": "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he's sure he'll be the first person to die there.",
	"year": 2011,
	"isbn": "9780553418026",
	"asin": "B00EMXBDMA",
	"tags": ["Sci-Fi", "Survival", "Hard Science Fiction"],
	"publisher": "Crown",
	"series": [],
	"authors": [{"name": "Andy Weir"}],
	"genres": [{"name": "Science Fiction"}],
	"narrators": [{"name": "R.C. Bray"}],
	"cover": "https://ia800505.us.archive.org/view_archive.php?archive=/35/items/l_covers_0014/l_covers_0014_64.zip&file=0014641755-L.jpg"
  },
  {
	"title": "The Primal Hunter",
	"description": "A world changed. An ancient system awakened. Jake, a corporate drone, finds himself in a tutorial that will change his life forever.",
	"year": 2022,
	"isbn": "9798834943709",
	"asin": "B09MV5TTSM",
	"tags": ["LitRPG", "Progression Fantasy", "Action"],
	"publisher": "Aethon Books",
	"series": [
		{
		"name": "The Primal Hunter",
		"index": "1"
		}
	],
	"authors": [{"name": "Zogarth"}],
	"genres": [{"name": "Fantasy"}, {"name": "LitRPG"}],
	"narrators": [{"name": "Travis Baldree"}]
  }
]
	`
