package database

const testData string = `
[
  {
    "title": "The Hunger Games",
    "description": "In the ruins of North America lies the nation of Panem, where twelve districts are forced to send tributes to a televised fight to the death.",
    "year": 2008,
    "isbn": "9780439023481",
    "asin": "B002MQYOFW",
    "tags": ["Dystopian", "Survival", "Young Adult"],
    "publisher": "Scholastic Press",
    "series": [{"name": "The Hunger Games", "index": "1"}],
    "authors": [{"name": "Suzanne Collins"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Tatiana Maslany"}]
  },
  {
    "title": "Catching Fire",
    "description": "Against all odds, Katniss Everdeen has won the annual Hunger Games. But the Capitol is angry and wants revenge.",
    "year": 2009,
    "isbn": "9780439023498",
    "asin": "B003O86FMW",
    "tags": ["Dystopian", "Revolution", "Young Adult"],
    "publisher": "Scholastic Press",
    "series": [{"name": "The Hunger Games", "index": "2"}],
    "authors": [{"name": "Suzanne Collins"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Tatiana Maslany"}]
  },
  {
    "title": "The Eye of the World",
    "description": "The Wheel of Time turns and Ages come and go, leaving memories that become legend.",
    "year": 1990,
    "isbn": "9781250251466",
    "asin": "B002U3CCYQ",
    "tags": ["Epic Fantasy", "High Fantasy"],
    "publisher": "Tor Books",
    "series": [{"name": "The Wheel of Time", "index": "1"}],
    "authors": [{"name": "Robert Jordan"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Michael Kramer"}, {"name": "Kate Reading"}]
  },
  {
    "title": "The Great Hunt",
    "description": "The hunt for the Horn of Valere begins as Rand al'Thor struggles with his destiny.",
    "year": 1990,
    "isbn": "9780312851408",
    "asin": "B004OC7IXM",
    "tags": ["Epic Fantasy", "Adventure"],
    "publisher": "Tor Books",
    "series": [{"name": "The Wheel of Time", "index": "2"}],
    "authors": [{"name": "Robert Jordan"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Michael Kramer"}, {"name": "Kate Reading"}]
  },
  {
    "title": "The Way of Kings",
    "description": "Roshar is a world of stone and storms where life has adapted accordingly.",
    "year": 2010,
    "isbn": "9780765365279",
    "asin": "B003P2S02M",
    "tags": ["Epic Fantasy", "Magic Systems"],
    "publisher": "Tor Books",
    "series": [{"name": "The Stormlight Archive", "index": "1"}],
    "authors": [{"name": "Brandon Sanderson"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Michael Kramer"}, {"name": "Kate Reading"}]
  },
  {
    "title": "Words of Radiance",
    "description": "The Knights Radiant must stand again as the True Desolation approaches.",
    "year": 2014,
    "isbn": "9780765326362",
    "asin": "B00E7V66O6",
    "tags": ["Epic Fantasy", "War"],
    "publisher": "Tor Books",
    "series": [{"name": "The Stormlight Archive", "index": "2"}],
    "authors": [{"name": "Brandon Sanderson"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Michael Kramer"}, {"name": "Kate Reading"}]
  },
  {
    "title": "Oathbringer",
    "description": "Dalinar Kholin faces the secrets of his past to unite a fractured world.",
    "year": 2017,
    "isbn": "9780765326379",
    "asin": "B01NAWAH85",
    "tags": ["Epic Fantasy", "Politics"],
    "publisher": "Tor Books",
    "series": [{"name": "The Stormlight Archive", "index": "3"}],
    "authors": [{"name": "Brandon Sanderson"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Michael Kramer"}, {"name": "Kate Reading"}]
  },
  {
    "title": "Red Rising",
    "description": "Darrow is a Red working the mines of Mars, unaware he is living a lie.",
    "year": 2014,
    "isbn": "9780345539793",
    "asin": "B00CVS2J80",
    "tags": ["Dystopian", "Sci-Fi"],
    "publisher": "Del Rey",
    "series": [{"name": "Red Rising Saga", "index": "1"}],
    "authors": [{"name": "Pierce Brown"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Tim Gerard Reynolds"}]
  },
  {
    "title": "Golden Son",
    "description": "Darrow continues his climb through the hierarchy of the Golds to destroy it from within.",
    "year": 2015,
    "isbn": "9780345539823",
    "asin": "B00I765ZEU",
    "tags": ["Space Opera", "Strategy"],
    "publisher": "Del Rey",
    "series": [{"name": "Red Rising Saga", "index": "2"}],
    "authors": [{"name": "Pierce Brown"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Tim Gerard Reynolds"}]
  },
  {
    "title": "Leviathan Wakes",
    "description": "A ship captain and a detective find themselves in a conspiracy that threatens the solar system.",
    "year": 2011,
    "isbn": "9780316129084",
    "asin": "B0047DVMR2",
    "tags": ["Space Opera", "Mystery"],
    "publisher": "Orbit",
    "series": [{"name": "The Expanse", "index": "1"}],
    "authors": [{"name": "James S. A. Corey"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Jefferson Mays"}]
  },
  {
    "title": "Caliban's War",
    "description": "War comes to the solar system as a monster is unleashed on Ganymede.",
    "year": 2012,
    "isbn": "9780316129060",
    "asin": "B0078XG9S6",
    "tags": ["Space Opera", "Action"],
    "publisher": "Orbit",
    "series": [{"name": "The Expanse", "index": "2"}],
    "authors": [{"name": "James S. A. Corey"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Jefferson Mays"}]
  },
  {
    "title": "Abaddon's Gate",
    "description": "A massive structure opens a gate to the unknown, drawing humanity into a new era.",
    "year": 2013,
    "isbn": "9780316129077",
    "asin": "B00B924Y9U",
    "tags": ["Space Opera", "Exploration"],
    "publisher": "Orbit",
    "series": [{"name": "The Expanse", "index": "3"}],
    "authors": [{"name": "James S. A. Corey"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Jefferson Mays"}]
  },
  {
    "title": "Project Hail Mary",
    "description": "A man wakes up on a spaceship with no memory and a mission to save Earth.",
    "year": 2021,
    "isbn": "9780593135204",
    "asin": "B08FHBV47V",
    "tags": ["Sci-Fi", "Problem Solving"],
    "publisher": "Ballantine Books",
    "series": [],
    "authors": [{"name": "Andy Weir"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Ray Porter"}]
  },
  {
    "title": "Circe",
    "description": "The daughter of Helios finds her power in witchcraft and is banished to a deserted island.",
    "year": 2018,
    "isbn": "9780316556347",
    "asin": "B0759S6F6L",
    "tags": ["Mythology", "Retelling"],
    "publisher": "Little, Brown",
    "series": [],
    "authors": [{"name": "Madeline Miller"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Perdita Weeks"}]
  },
  {
    "title": "The Night Circus",
    "description": "Two young magicians are pitted against each other in a venue that only appears at night.",
    "year": 2011,
    "isbn": "9780307744432",
    "asin": "B004S0TWRU",
    "tags": ["Fantasy", "Romance"],
    "publisher": "Anchor",
    "series": [],
    "authors": [{"name": "Erin Morgenstern"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Jim Dale"}]
  },
  {
    "title": "Atomic Habits",
    "description": "A guide to building good habits and breaking bad ones through small changes.",
    "year": 2018,
    "isbn": "9780735211292",
    "asin": "B07D23CFGR",
    "tags": ["Self-Help", "Productivity"],
    "publisher": "Avery",
    "series": [],
    "authors": [{"name": "James Clear"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "James Clear"}]
  },
  {
    "title": "Where the Crawdads Sing",
    "description": "A young girl growing up in the marsh of North Carolina becomes a murder suspect.",
    "year": 2018,
    "isbn": "9780735219090",
    "asin": "B078N29M55",
    "tags": ["Mystery", "Nature"],
    "publisher": "G.P. Putnam's Sons",
    "series": [],
    "authors": [{"name": "Delia Owens"}],
    "genres": [{"name": "Fiction"}],
    "narrators": [{"name": "Cassandra Campbell"}]
  },
  {
    "title": "Educated",
    "description": "A memoir about a woman born to survivalists who leaves her isolated family to pursue an education.",
    "year": 2018,
    "isbn": "9780399590504",
    "asin": "B072BLVM83",
    "tags": ["Memoir", "Inspiration"],
    "publisher": "Random House",
    "series": [],
    "authors": [{"name": "Tara Westover"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Julia Whelan"}]
  },
  {
    "title": "The Silent Patient",
    "description": "A woman shoots her husband and then never speaks another word.",
    "year": 2019,
    "isbn": "9781250301697",
    "asin": "B07H76B69T",
    "tags": ["Thriller", "Psychological"],
    "publisher": "Celadon Books",
    "series": [],
    "authors": [{"name": "Alex Michaelides"}],
    "genres": [{"name": "Fiction"}],
    "narrators": [{"name": "Louise Brealey"}]
  },
  {
    "title": "Tomorrow, and Tomorrow, and Tomorrow",
    "description": "Two friends collaborate on video game design over thirty years.",
    "year": 2022,
    "isbn": "9780593321201",
    "asin": "B09G967T6L",
    "tags": ["Contemporary", "Gaming"],
    "publisher": "Knopf",
    "series": [],
    "authors": [{"name": "Gabrielle Zevin"}],
    "genres": [{"name": "Fiction"}],
    "narrators": [{"name": "Jennifer Lim"}]
  },
  {
    "title": "The Martian",
    "description": "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he's sure he'll be the first person to die there.",
    "year": 2011,
    "isbn": "9780553418026",
    "asin": "B00EMXBDMA",
    "tags": ["Sci-Fi", "Survival", "Hard Science Fiction"],
    "publisher": "Crown",
    "series": [],
    "authors": [{"name": "Andy Weir"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "R.C. Bray"}],
    "cover": "https://ia800505.us.archive.org/view_archive.php?archive=/35/items/l_covers_0014/l_covers_0014_64.zip&file=0014641755-L.jpg"
  },
  {
    "title": "Harry Potter and the Philosopher's Stone",
    "description": "A young boy discovers he is a wizard and attends a magical boarding school.",
    "year": 1997,
    "isbn": "9780747532699",
    "asin": "B0192CT0ZK",
    "tags": ["Magic", "Wizarding World", "YA"],
    "publisher": "Bloomsbury",
    "series": [{"name": "Harry Potter", "index": "1"}],
    "authors": [{"name": "J.K. Rowling"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Stephen Fry"}]
  },
  {
    "title": "Harry Potter and the Chamber of Secrets",
    "description": "Harry returns for his second year to find a mysterious chamber has been opened.",
    "year": 1998,
    "isbn": "9780747538493",
    "asin": "B0192CT08G",
    "tags": ["Magic", "Mystery", "YA"],
    "publisher": "Bloomsbury",
    "series": [{"name": "Harry Potter", "index": "2"}],
    "authors": [{"name": "J.K. Rowling"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Stephen Fry"}]
  },
  {
    "title": "The Primal Hunter",
    "description": "An office worker is thrust into a multiverse-spanning tutorial where only the strong survive.",
    "year": 2022,
    "isbn": "9798426232426",
    "asin": "B09MWP4277",
    "tags": ["LitRPG", "Progression Fantasy", "System"],
    "publisher": "Aethon Books",
    "series": [{"name": "The Primal Hunter", "index": "1"}],
    "authors": [{"name": "Zogarth"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Travis Baldree"}]
  },
  {
    "title": "The Primal Hunter 2",
    "description": "Jake continues his journey through the tutorial, honing his skills as a predator.",
    "year": 2022,
    "isbn": "9798831411515",
    "asin": "B09R6QCZ4M",
    "tags": ["LitRPG", "Progression Fantasy", "Action"],
    "publisher": "Aethon Books",
    "series": [{"name": "The Primal Hunter", "index": "2"}],
    "authors": [{"name": "Zogarth"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Travis Baldree"}]
  },
  {
    "title": "The Fellowship of the Ring",
    "description": "A young hobbit is tasked with destroying a powerful ring to save Middle-earth.",
    "year": 1954,
    "isbn": "9780618346257",
    "asin": "B007978OY6",
    "tags": ["Epic Fantasy", "High Fantasy", "Quest"],
    "publisher": "George Allen & Unwin",
    "series": [{"name": "The Lord of the Rings", "index": "1"}],
    "authors": [{"name": "J.R.R. Tolkien"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Andy Serkis"}]
  },
  {
    "title": "The Two Towers",
    "description": "The fellowship is broken as the war for Middle-earth intensifies.",
    "year": 1954,
    "isbn": "9780618346264",
    "asin": "B007978NPG",
    "tags": ["Epic Fantasy", "War", "Adventure"],
    "publisher": "George Allen & Unwin",
    "series": [{"name": "The Lord of the Rings", "index": "2"}],
    "authors": [{"name": "J.R.R. Tolkien"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Andy Serkis"}]
  },
  {
    "title": "The Final Empire",
    "description": "In a world where ash falls from the sky, a street urchin learns she has the power of Allomancy.",
    "year": 2006,
    "isbn": "9780765311788",
    "asin": "B002GYI9C0",
    "tags": ["Magic System", "Heist", "Epic Fantasy"],
    "publisher": "Tor Books",
    "series": [{"name": "Mistborn", "index": "1"}],
    "authors": [{"name": "Brandon Sanderson"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Michael Kramer"}]
  },
  {
    "title": "The Well of Ascension",
    "description": "The struggle for a new government begins after the fall of the Lord Ruler.",
    "year": 2007,
    "isbn": "9780765316882",
    "asin": "B002G09VLO",
    "tags": ["Politics", "Magic", "Siege"],
    "publisher": "Tor Books",
    "series": [{"name": "Mistborn", "index": "2"}],
    "authors": [{"name": "Brandon Sanderson"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Michael Kramer"}]
  },
  {
    "title": "Dungeon Crawler Carl",
    "description": "The apocalypse is televised as a man and his cat must survive a deadly alien dungeon.",
    "year": 2020,
    "isbn": "9780593820247",
    "asin": "B08BKGYQXW",
    "tags": ["LitRPG", "Humor", "Post-Apocalyptic"],
    "publisher": "Matt Dinniman",
    "series": [{"name": "Dungeon Crawler Carl", "index": "1"}],
    "authors": [{"name": "Matt Dinniman"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Jeff Hays"}]
  },
  {
    "title": "Carl's Doomsday Scenario",
    "description": "The second floor of the dungeon is even deadlier as Carl and Princess Donut level up.",
    "year": 2021,
    "isbn": "9780593820261",
    "asin": "B08V2C3Z2Z",
    "tags": ["LitRPG", "Humor", "Action"],
    "publisher": "Matt Dinniman",
    "series": [{"name": "Dungeon Crawler Carl", "index": "2"}],
    "authors": [{"name": "Matt Dinniman"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Jeff Hays"}]
  },
  {
    "title": "The Alchemist",
    "description": "A shepherd boy travels to Egypt in search of a hidden treasure.",
    "year": 1988,
    "isbn": "9780062315007",
    "asin": "B000OCXGVG",
    "tags": ["Adventure", "Philosophy"],
    "publisher": "HarperCollins",
    "series": [],
    "authors": [{"name": "Paulo Coelho"}],
    "genres": [{"name": "Fiction"}],
    "narrators": [{"name": "Jeremy Irons"}]
  },
  {
    "title": "Neuromancer",
    "description": "A washed-up computer hacker is hired by a mysterious employer for one last job.",
    "year": 1984,
    "isbn": "9780441569595",
    "asin": "B000O76ON6",
    "tags": ["Cyberpunk", "Artificial Intelligence"],
    "publisher": "Ace",
    "series": [],
    "authors": [{"name": "William Gibson"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Robertson Dean"}]
  },
  {
    "title": "Dune",
    "description": "A young nobleman becomes the leader of a desert planet's native people.",
    "year": 1965,
    "isbn": "9780441172719",
    "asin": "B00B247AK0",
    "tags": ["Space Opera", "Politics", "Religion"],
    "publisher": "Chilton Books",
    "series": [{"name": "Dune", "index": "1"}],
    "authors": [{"name": "Frank Herbert"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "George Guidall"}]
  },
  {
    "title": "1984",
    "description": "A man rebels against a totalitarian regime that watches every move.",
    "year": 1949,
    "isbn": "9780451524935",
    "asin": "B003JTHWKU",
    "tags": ["Dystopian", "Politics"],
    "publisher": "Secker & Warburg",
    "series": [],
    "authors": [{"name": "George Orwell"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Simon Prebble"}]
  },
  {
    "title": "Brave New World",
    "description": "A futuristic society is governed by efficiency and consumerism.",
    "year": 1932,
    "isbn": "9780060850524",
    "asin": "B003XRELGQ",
    "tags": ["Dystopian", "Social Science"],
    "publisher": "Chatto & Windus",
    "series": [],
    "authors": [{"name": "Aldous Huxley"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Michael York"}]
  },
  {
    "title": "The Road",
    "description": "A father and son walk through a post-apocalyptic landscape.",
    "year": 2006,
    "isbn": "9780307387899",
    "asin": "B000OI0G1Q",
    "tags": ["Post-Apocalyptic", "Survival"],
    "publisher": "Knopf",
    "series": [],
    "authors": [{"name": "Cormac McCarthy"}],
    "genres": [{"name": "Fiction"}],
    "narrators": [{"name": "Tom Stechschulte"}]
  },
  {
    "title": "The Hitchhiker's Guide to the Galaxy",
    "description": "Arthur Dent is rescued from Earth seconds before it's destroyed.",
    "year": 1979,
    "isbn": "9780345391803",
    "asin": "B000XUBC2C",
    "tags": ["Comedy", "Space", "Satire"],
    "publisher": "Pan Books",
    "series": [{"name": "Hitchhiker's Guide", "index": "1"}],
    "authors": [{"name": "Douglas Adams"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Stephen Fry"}]
  },
  {
    "title": "Hyperion",
    "description": "Seven pilgrims share their stories as they travel to the Shrike.",
    "year": 1989,
    "isbn": "9780553283686",
    "asin": "B004G600XY",
    "tags": ["Space Opera", "Philosophy"],
    "publisher": "Bantam Spectra",
    "series": [{"name": "Hyperion Cantos", "index": "1"}],
    "authors": [{"name": "Dan Simmons"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Marc Vietor"}]
  },
  {
    "title": "The Name of the Wind",
    "description": "A legendary figure recounts his life story to a traveling scribe.",
    "year": 2007,
    "isbn": "9780756404741",
    "asin": "B0010SKUYM",
    "tags": ["Magic", "Music", "Education"],
    "publisher": "DAW Books",
    "series": [{"name": "The Kingkiller Chronicle", "index": "1"}],
    "authors": [{"name": "Patrick Rothfuss"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Nick Podehl"}]
  },
  {
    "title": "Good Omens",
    "description": "An angel and a demon team up to prevent the apocalypse.",
    "year": 1990,
    "isbn": "9780060853969",
    "asin": "B0054LJGMA",
    "tags": ["Comedy", "Religion", "Modern Fantasy"],
    "publisher": "Gollancz",
    "series": [],
    "authors": [{"name": "Terry Pratchett"}, {"name": "Neil Gaiman"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Rebecca Front"}]
  },
  {
    "title": "The Blade Itself",
    "description": "A barbarian, a nobleman, and a torturer find their fates intertwined.",
    "year": 2006,
    "isbn": "9781591025337",
    "asin": "B002V92X8K",
    "tags": ["Grimdark", "Character-Driven"],
    "publisher": "Gollancz",
    "series": [{"name": "The First Law", "index": "1"}],
    "authors": [{"name": "Joe Abercrombie"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Steven Pacey"}]
  },
  {
    "title": "Foundation",
    "description": "A mathematician predicts the fall of a galactic empire and creates a plan to save knowledge.",
    "year": 1951,
    "isbn": "9780553293357",
    "asin": "B000FC1P06",
    "tags": ["Space Opera", "Psychohistory"],
    "publisher": "Gnome Press",
    "series": [{"name": "Foundation", "index": "1"}],
    "authors": [{"name": "Isaac Asimov"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Scott Brick"}]
  },
  {
    "title": "American Gods",
    "description": "A man released from prison becomes the bodyguard for a mysterious con man.",
    "year": 2001,
    "isbn": "9780380973651",
    "asin": "B004L269S2",
    "tags": ["Mythology", "Road Trip", "Urban Fantasy"],
    "publisher": "Headline",
    "series": [],
    "authors": [{"name": "Neil Gaiman"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "George Guidall"}]
  },
  {
    "title": "Sapiens",
    "description": "A brief history of humankind from the Stone Age to the present.",
    "year": 2011,
    "isbn": "9780062316097",
    "asin": "B00K6G26X0",
    "tags": ["History", "Anthropology"],
    "publisher": "Harper",
    "series": [],
    "authors": [{"name": "Yuval Noah Harari"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Derek Perkins"}]
  },
  {
    "title": "Thinking, Fast and Slow",
    "description": "An exploration of the two systems that drive the way we think.",
    "year": 2011,
    "isbn": "9780374275631",
    "asin": "B00555X8OA",
    "tags": ["Psychology", "Decision Making"],
    "publisher": "Farrar, Straus and Giroux",
    "series": [],
    "authors": [{"name": "Daniel Kahneman"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Patrick Egan"}]
  },
  {
    "title": "The Color of Magic",
    "description": "The first book in the Discworld series, featuring a wizard and a tourist.",
    "year": 1983,
    "isbn": "9780861403240",
    "asin": "B00354YAUE",
    "tags": ["Comedy", "Satire", "Magic"],
    "publisher": "Colin Smythe",
    "series": [{"name": "Discworld", "index": "1"}],
    "authors": [{"name": "Terry Pratchett"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Colin Morgan"}]
  },
  {
    "title": "Ender's Game",
    "description": "A young boy is trained in a space military school to lead Earth's defense.",
    "year": 1985,
    "isbn": "9780312932084",
    "asin": "B003G4W49C",
    "tags": ["Military Sci-Fi", "Warfare"],
    "publisher": "Tor Books",
    "series": [{"name": "Ender's Saga", "index": "1"}],
    "authors": [{"name": "Orson Scott Card"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Stefan Rudnicki"}]
  },
  {
    "title": "Ready Player One",
    "description": "In a dystopian future, people spend most of their time in a virtual world called the OASIS.",
    "year": 2011,
    "isbn": "9780307887436",
    "asin": "B004J4WKUQ",
    "tags": ["Cyberpunk", "Gaming", "80s Pop Culture"],
    "publisher": "Crown",
    "series": [{"name": "Ready Player One", "index": "1"}],
    "authors": [{"name": "Ernest Cline"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "Wil Wheaton"}]
  },
  {
    "title": "The Shadow of the Torturer",
    "description": "A young apprentice in the Guild of Torturers is exiled for showing mercy.",
    "year": 1980,
    "isbn": "9780671415174",
    "asin": "B00C4BA59C",
    "tags": ["Dying Earth", "Literary Fantasy"],
    "publisher": "Pocket Books",
    "series": [{"name": "The Book of the New Sun", "index": "1"}],
    "authors": [{"name": "Gene Wolfe"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Jonathan Davis"}]
  },
  {
    "title": "He Who Fights with Monsters",
    "description": "Jason is transported to a new world and gains unusual powers based on his gaming habits.",
    "year": 2021,
    "isbn": "9798200542383",
    "asin": "B08WCT9W26",
    "tags": ["LitRPG", "Progression Fantasy", "Humor"],
    "publisher": "Shirtaloon",
    "series": [{"name": "He Who Fights with Monsters", "index": "1"}],
    "authors": [{"name": "Shirtaloon"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Heath Miller"}]
  },
  {
    "title": "Storm Front",
    "description": "The first case for Harry Dresden, Chicago's only professional wizard.",
    "year": 2000,
    "isbn": "9780345506399",
    "asin": "B000S1M4DU",
    "tags": ["Urban Fantasy", "Detective", "Mystery"],
    "publisher": "Roc Books",
    "series": [{"name": "The Dresden Files", "index": "1"}],
    "authors": [{"name": "Jim Butcher"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "James Marsters"}]
  },
  {
    "title": "Old Man's War",
    "description": "In the future, elderly humans are recruited to fight in space in exchange for new bodies.",
    "year": 2005,
    "isbn": "9780765309402",
    "asin": "B0009U771W",
    "tags": ["Military Sci-Fi", "Space"],
    "publisher": "Tor Books",
    "series": [{"name": "Old Man's War", "index": "1"}],
    "authors": [{"name": "John Scalzi"}],
    "genres": [{"name": "Science Fiction"}],
    "narrators": [{"name": "William Dufris"}]
  },
  {
    "title": "A Game of Thrones",
    "description": "Noble houses compete for control of the Iron Throne while a threat rises in the north.",
    "year": 1996,
    "isbn": "9780553103540",
    "asin": "B000GR71W6",
    "tags": ["Epic Fantasy", "Politics", "War"],
    "publisher": "Bantam Spectra",
    "series": [{"name": "A Song of Ice and Fire", "index": "1"}],
    "authors": [{"name": "George R.R. Martin"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Roy Dotrice"}]
  },
  {
    "title": "Mistborn: The Hero of Ages",
    "description": "The conclusion to the Mistborn trilogy as Vin faces the ultimate threat.",
    "year": 2008,
    "isbn": "9780765316899",
    "asin": "B002G09VM8",
    "tags": ["Epic Fantasy", "Gods", "Magic"],
    "publisher": "Tor Books",
    "series": [{"name": "Mistborn", "index": "3"}],
    "authors": [{"name": "Brandon Sanderson"}],
    "genres": [{"name": "Fantasy"}],
    "narrators": [{"name": "Michael Kramer"}]
  },
  {
    "title": "Kitchen Confidential",
    "description": "An unfiltered look into the professional culinary world.",
    "year": 2000,
    "isbn": "9780060899226",
    "asin": "B000SF0R6A",
    "tags": ["Culinary", "Memoir", "Industry"],
    "publisher": "Bloomsbury",
    "series": [],
    "authors": [{"name": "Anthony Bourdain"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Anthony Bourdain"}]
  },
  {
    "title": "The 7 Habits of Highly Effective People",
    "description": "A business and self-help book focused on personal and interpersonal effectiveness.",
    "year": 1989,
    "isbn": "9780743272452",
    "tags": ["Self-Help", "Business", "Leadership"],
    "publisher": "Free Press",
    "series": [],
    "authors": [{"name": "Stephen R. Covey"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Stephen R. Covey"}]
  },
  {
    "title": "The Power of Habit",
    "description": "Why we do what we do in life and business.",
    "year": 2012,
    "isbn": "9781400069286",
    "asin": "B005P1YE9E",
    "tags": ["Psychology", "Behavioral Science"],
    "publisher": "Random House",
    "series": [],
    "authors": [{"name": "Charles Duhigg"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Mike Chamberlain"}]
  },
  {
    "title": "Outliers",
    "description": "The story of success and what makes high-achievers different.",
    "year": 2008,
    "isbn": "9780316017923",
    "asin": "B001ANYDAO",
    "tags": ["Sociology", "Psychology", "Success"],
    "publisher": "Little, Brown and Company",
    "series": [],
    "authors": [{"name": "Malcolm Gladwell"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Malcolm Gladwell"}]
  },
  {
    "title": "The Subtle Art of Not Giving a F*ck",
    "description": "A counterintuitive approach to living a good life.",
    "year": 2016,
    "isbn": "9780062457714",
    "asin": "B019MMUA8S",
    "tags": ["Self-Help", "Personal Growth"],
    "publisher": "HarperOne",
    "series": [],
    "authors": [{"name": "Mark Manson"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Roger Wayne"}]
  },
  {
    "title": "Guns, Germs, and Steel",
    "description": "The fates of human societies and how geography shaped history.",
    "year": 1997,
    "isbn": "9780393038910",
    "tags": ["History", "Evolution"],
    "publisher": "W.W. Norton",
    "series": [],
    "authors": [{"name": "Jared Diamond"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Doug Ordunio"}]
  },
  {
    "title": "Quiet: The Power of Introverts",
    "description": "How introverts are undervalued in a world that can't stop talking.",
    "year": 2012,
    "isbn": "9780307352149",
    "asin": "B0047Y1776",
    "tags": ["Psychology", "Introversion"],
    "publisher": "Crown",
    "series": [],
    "authors": [{"name": "Susan Cain"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Kathe Mazur"}]
  },
  {
    "title": "The Lean Startup",
    "description": "How today's entrepreneurs use continuous innovation to create successful businesses.",
    "year": 2011,
    "isbn": "9780307887894",
    "asin": "B004J4XGN6",
    "tags": ["Business", "Entrepreneurship"],
    "publisher": "Crown",
    "series": [],
    "authors": [{"name": "Eric Ries"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Eric Ries"}]
  },
  {
    "title": "Man's Search for Meaning",
    "description": "A psychiatrist's memoir of life in Nazi death camps and his discovery of logotherapy.",
    "year": 1946,
    "isbn": "9780807014295",
    "asin": "B002KOKT3E",
    "tags": ["Psychology", "Philosophy", "Holocaust"],
    "publisher": "Beacon Press",
    "series": [],
    "authors": [{"name": "Viktor Frankl"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Simon Vance"}]
  },
  {
    "title": "The Devil in the White City",
    "description": "The story of the 1893 World's Fair and the serial killer who used it to lure victims.",
    "year": 2003,
    "isbn": "9780609608449",
    "tags": ["True Crime", "History"],
    "publisher": "Crown",
    "series": [],
    "authors": [{"name": "Erik Larson"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Scott Brick"}]
  },
  {
    "title": "Into Thin Air",
    "description": "A personal account of the 1996 Mount Everest disaster.",
    "year": 1997,
    "isbn": "9780375502804",
    "tags": ["Memoir", "Adventure", "Disaster"],
    "publisher": "Villard",
    "series": [],
    "authors": [{"name": "Jon Krakauer"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Jon Krakauer"}]
  },
  {
    "title": "The Immortal Life of Henrietta Lacks",
    "description": "The story of a woman whose cancer cells became one of the most important tools in medicine.",
    "year": 2010,
    "isbn": "9781400052172",
    "asin": "B00338QENI",
    "tags": ["Science", "Ethics", "Biography"],
    "publisher": "Crown",
    "series": [],
    "authors": [{"name": "Rebecca Skloot"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Bahni Turpin"}]
  },
  {
    "title": "The Glass Castle",
    "description": "A memoir of resilience and redemption, and a look into a dysfunctional family.",
    "year": 2005,
    "isbn": "9780743247542",
    "tags": ["Memoir", "Family"],
    "publisher": "Scribner",
    "series": [],
    "authors": [{"name": "Jeannette Walls"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Jeannette Walls"}]
  },
  {
    "title": "When Breath Becomes Air",
    "description": "A neurosurgeon's memoir about facing a terminal lung cancer diagnosis.",
    "year": 2016,
    "isbn": "9780812988406",
    "asin": "B015NCY22W",
    "tags": ["Memoir", "Medicine", "Philosophy"],
    "publisher": "Random House",
    "series": [],
    "authors": [{"name": "Paul Kalanithi"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Sunil Malhotra"}]
  },
  {
    "title": "Born a Crime",
    "description": "Stories from a South African childhood during and after apartheid.",
    "year": 2016,
    "isbn": "9780399588174",
    "asin": "B01IW9TQPK",
    "tags": ["Memoir", "Humor", "History"],
    "publisher": "Spiegel & Grau",
    "series": [],
    "authors": [{"name": "Trevor Noah"}],
    "genres": [{"name": "Nonfiction"}],
    "narrators": [{"name": "Trevor Noah"}]
  }
]
	`
